heat_template_version: 2014-10-16


description: >
  OpenShift Master


parameters:

  key_name:
    type: string
    constraints:
    - custom_constraint: nova.keypair

  image:
    type: string
    constraints:
    - custom_constraint: glance.image

  flavor:
    type: string
    constraints:
    - custom_constraint: nova.flavor

  dns_ip:
    type: string
    description: IP address of the DNS server

  docker_volume_size:
    type: number
    description: >
      size of a cinder volume in GB to allocate to docker for container/image
      storage
    default: 25

  rhn_username:
    type: string

  rhn_password:
    type: string
    hidden: true

  rhn_pool:
    type: string
    hidden: true

  deployment_type:
    type: string

  port:
    description: >
      Neutron port (with a floating IP address) to assign to the OpenShift
      Master Nova Server
    type: string

  hostname:
    type: string

  domain_name:
    type: string

  floating_ip:
    type: string

  ansible_public_key:
    type: string

  ansible_private_key:
    type: string

  node_hostnames:
    type: string
    default: ''

  ssh_user:
    type: string

  openshift_ansible_git_url:
    type: string

  openshift_ansible_git_rev:
    type: string

  os_auth_url:
    type: string

  os_username:
    type: string

  os_password:
    type: string
    hidden: true

  os_tenant_id:
    type: string

  os_region_name:
    type: string

  identity_provider:
    type: string

  timeout:
    description: Time to wait until the master setup is ready.
    type: number
    default: 4000

resources:

  config_agent:
    type: collect-config-setup/install_config_agent_centos_yum.yaml

  host:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: "HOST.DOMAIN"
          params:
            HOST: {get_param: hostname}
            DOMAIN: {get_param: domain_name}
      admin_user: {get_param: ssh_user}
      image: {get_param: image}
      flavor: {get_param: flavor}
      key_name: {get_param: key_name}
      networks:
      - port: {get_param: port}
      user_data_format: SOFTWARE_CONFIG
      user_data: {get_resource: init}

  docker_volume:
    type: OS::Cinder::Volume
    properties:
      size: {get_param: docker_volume_size}

  docker_volume_attach:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: {get_resource: host}
      volume_id: {get_resource: docker_volume}

  init:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_attr: [config_agent, config]}
        type: multipart
      - config: {get_resource: set_hostname}
      - config: {get_resource: included_files}
      - config: {get_resource: rhn_register}
      - config: {get_resource: master_boot}

  set_hostname:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        hostname: {get_param: hostname}
        fqdn:
          str_replace:
            template: "HOST.DOMAIN"
            params:
              HOST: {get_param: hostname}
              DOMAIN: {get_param: domain_name}

  included_files:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        write_files:
        - path: /etc/hosts
          content:
            str_replace:
              params:
                $NODE_IP: {get_param: floating_ip}
                $NODE_HOSTNAME: {get_param: hostname}
                $NODE_DOMAIN: {get_param: domain_name}
              template: {get_file: fragments/etc-node-hosts}
        - path: /root/.ssh/id_rsa
          permissions: 0600
          content: {get_param: ansible_private_key}
        - path: /root/.ssh/id_rsa.pub
          permissions: 0600
          content: {get_param: ansible_public_key}
        - path: /usr/bin/retry
          permissions: 0755
          content: {get_file: fragments/retry.sh}
        ssh_authorized_keys:
        - {get_param: ansible_public_key}

  rhn_register:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          params:
            $RHN_USERNAME: {get_param: rhn_username}
            $RHN_PASSWORD: {get_param: rhn_password}
            $POOL_ID: {get_param: rhn_pool}
          template: {get_file: fragments/rhn-register.sh}

  master_boot:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          params:
            $DNS_IP: {get_param: dns_ip}
            $MASTER_IP: {get_param: floating_ip}
            $OPENSHIFT_ANSIBLE_GIT_URL: {get_param: openshift_ansible_git_url}
            $OPENSHIFT_ANSIBLE_GIT_REV: {get_param: openshift_ansible_git_rev}
            $WC_NOTIFY: { get_attr: ['wait_handle', 'curl_cli'] }
          template: {get_file: fragments/master-boot.sh}

  run_ansible:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
        - name: node_hostname
      config:
        str_replace:
          params:
            $MASTER_HOSTNAME: {get_param: hostname}
            $DOMAINNAME: {get_param: domain_name}
            $NODE_HOSTNAME: $node_hostname
            $SSH_USER: {get_param: ssh_user}
            $DEPLOYMENT_TYPE: {get_param: deployment_type}
            $OS_AUTH_URL: {get_param: os_auth_url}
            $OS_USERNAME: {get_param: os_username}
            $OS_PASSWORD: {get_param: os_password}
            $OS_TENANT_ID: {get_param: os_tenant_id}
            $OS_REGION_NAME: {get_param: os_region_name}
            $IDENTITY_PROVIDER: {get_param: identity_provider}
          template: {get_file: fragments/master-ansible.sh}

  wait_condition:
    type: OS::Heat::WaitCondition
    properties:
      handle: {get_resource: wait_handle}
      timeout: {get_param: timeout}

  wait_handle:
    type: OS::Heat::WaitConditionHandle

outputs:
  console_url:
    value:
      str_replace:
        params:
          HOSTNAME: {get_param: hostname}
          DOMAINNAME: {get_param: domain_name}
        template: "https://HOSTNAME.DOMAINNAME:8443/console/"
  api_url:
    value:
      str_replace:
        params:
          HOSTNAME: {get_param: hostname}
          DOMAINNAME: {get_param: domain_name}
        template: "https://HOSTNAME.DOMAINNAME:8443/"
  wc_data:
    value: { get_attr: ['wait_condition', 'data'] }
