heat_template_version: 2014-10-16


description: >
  OpenShift Node


parameters:

  key_name:
    type: string
    constraints:
    - custom_constraint: nova.keypair

  image:
    type: string
    constraints:
    - custom_constraint: glance.image

  flavor:
    type: string
    constraints:
    - custom_constraint: nova.flavor

  external_network:
    type: string
    constraints:
    - custom_constraint: neutron.network

  fixed_network:
    type: string
    constraints:
    - custom_constraint: neutron.network

  fixed_subnet:
    type: string
    constraints:
    - custom_constraint: neutron.subnet

  container_network:
    type: string
    constraints:
    - custom_constraint: neutron.network

  container_subnet:
    type: string
    constraints:
    - custom_constraint: neutron.subnet

  container_security_group:
    type: string

  dns_ip:
    type: string
    description: IP address of the DNS server

  rhn_username:
    type: string

  rhn_password:
    type: string
    hidden: true

  hostname_prefix:
    type: string

  ansible_public_key:
    type: string

  ssh_user:
    type: string


resources:

  random_hostname_suffix:
    type: OS::Heat::RandomString
    properties:
      character_classes: [{"min": 5, "class": "lowercase"}]
      length: 5

  host:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: "HOST-SUFFIX.example.com"
          params:
            HOST: {get_param: hostname_prefix}
            SUFFIX: {get_attr: [random_hostname_suffix, value]}
      admin_user: {get_param: ssh_user}
      image: {get_param: image}
      flavor: {get_param: flavor}
      key_name: {get_param: key_name}
      networks:
      - port: {get_resource: port}
      - port: {get_resource: container_port}
      user_data_format: SOFTWARE_CONFIG
      user_data: {get_resource: init}

  container_port:
    type: OS::Neutron::Port
    properties:
      network: {get_param: container_network}
      fixed_ips:
      - subnet: {get_param: container_subnet}
      replacement_policy: AUTO
      value_specs:
        port_security_enabled: false

  init:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: set_hostname}
      - config: {get_resource: included_files}
      - config: {get_resource: rhn_register}
      - config: {get_resource: node_boot}

  set_hostname:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        hostname:
          str_replace:
            template: "HOST-SUFFIX.example.com"
            params:
              HOST: {get_param: hostname_prefix}
              SUFFIX: {get_attr: [random_hostname_suffix, value]}
        fqdn:
          str_replace:
            template: "HOST-SUFFIX.example.com"
            params:
              HOST: {get_param: hostname_prefix}
              SUFFIX: {get_attr: [random_hostname_suffix, value]}

  included_files:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        ssh_authorized_keys:
        - {get_param: ansible_public_key}
        write_files:
        - path: /usr/bin/retry
          permissions: 0755
          content: {get_file: fragments/retry.sh}
        - path: /etc/hosts
          content:
            str_replace:
              params:
                $NODE_IP: {get_attr: [floating_ip, floating_ip_address]}
                $NODE_HOSTNAME:
                  str_replace:
                    template: "HOST-SUFFIX.example.com"
                    params:
                      HOST: {get_param: hostname_prefix}
                      SUFFIX: {get_attr: [random_hostname_suffix, value]}
              template: {get_file: fragments/etc-node-hosts}
        - path: /etc/sysconfig/network-scripts/ifcfg-eth1
          content:
            str_replace:
              params:
                $IPADDR: {get_attr: [container_port, fixed_ips, 0, ip_address]}
                $HWADDR: {get_attr: [container_port, mac_address]}
              template: {get_file: fragments/ifcfg-eth1}

  rhn_register:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          params:
            $RHN_USERNAME: {get_param: rhn_username}
            $RHN_PASSWORD: {get_param: rhn_password}
          template: {get_file: fragments/rhn-register.sh}

  node_boot:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          params:
            $DNS_IP: {get_param: dns_ip}
          template: {get_file: fragments/node-boot.sh}

  port:
    type: OS::Neutron::Port
    properties:
      security_groups:
      - {get_resource: security_group}
      network: {get_param: fixed_network}
      fixed_ips:
      - subnet: {get_param: fixed_subnet}
      replacement_policy: AUTO

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
      - protocol: icmp
      # Just open everything for now:
      - protocol: tcp
        port_range_min: 0
        port_range_max: 65535
      - protocol: udp
        port_range_min: 0
        port_range_max: 65535

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: {get_param: external_network}
      port_id: {get_resource: port}


outputs:
  hostname:
    description: Hostname of this OpenShift node
    value:
      str_replace:
        template: "HOST-SUFFIX.example.com"
        params:
          HOST: {get_param: hostname_prefix}
          SUFFIX: {get_attr: [random_hostname_suffix, value]}
  etc_hosts:
    description: A hostname/IP entry for /etc/hosts
    value:
      str_replace:
        template: "IP HOST-SUFFIX.example.com"
        params:
          IP: {get_attr: [floating_ip, floating_ip_address]}
          HOST: {get_param: hostname_prefix}
          SUFFIX: {get_attr: [random_hostname_suffix, value]}
  ip_address:
    description: IP address of the node
    value: {get_attr: [floating_ip, floating_ip_address]}

